# === FAT IMAGE ===
FROM python:3.9

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо всі файли проєкту
COPY . /app

# Встановлюємо залежності
RUN pip install --upgrade pip
RUN pip install torch torchvision pillow

# Запуск inference-сервісу
CMD ["python", "inference.py"]
